[workspace]
name = "projectname"
authors = ["Projectname Team"]
version = "0.0.0"
channels = [
    "conda-forge",
]

platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]
# "test" = { cmd = ["python", "./test.py"] }
"build" = { cmd = ["cargo", "build"] }

[dependencies]
# "python" = "*"
"rust" = "1.92.*"
"git" = "*"

# [pypi-dependencies]
# kas = "~=4.8.1"

# [feature.build.tasks]
# build = { cmd = ["cmake", "-S", ".", "-B", "build"]}
# [feature.build.dependencies]
# "python-clang" = "20.1.5.*"

# [feature.build.target.linux-arm64.dependencies]
# "gcc" = "*"
# [feature.build.target.osx-64.dependencies]
# "clang" = "*"
# [feature.build.target.win-64.dependencies]
# "clang" = "*"

# [environments]
# build = ["build"]
